// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZF9Q0VvDW8UtZNQ5m3hkSc2B66vdpGM',
    appId: '1:316349124552:web:73338af836f51bf37dfafd',
    messagingSenderId: '316349124552',
    projectId: 'arcloudanchor-12fd3',
    authDomain: 'arcloudanchor-12fd3.firebaseapp.com',
    databaseURL:
        'https://arcloudanchor-12fd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcloudanchor-12fd3.firebasestorage.app',
    measurementId: 'G-4LZTZQ2PTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmMTAEI_PF1vmuXtepmYzydP_jyM45jw',
    appId: '1:316349124552:android:e7ac07fee47175947dfafd',
    messagingSenderId: '316349124552',
    projectId: 'arcloudanchor-12fd3',
    databaseURL:
        'https://arcloudanchor-12fd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcloudanchor-12fd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAojh7OWbeEqp2Wo6nWF2J9dBIJchOTk',
    appId: '1:316349124552:ios:d50537efefb0cec37dfafd',
    messagingSenderId: '316349124552',
    projectId: 'arcloudanchor-12fd3',
    databaseURL:
        'https://arcloudanchor-12fd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcloudanchor-12fd3.firebasestorage.app',
    iosBundleId: 'com.example.tagnarMerchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAojh7OWbeEqp2Wo6nWF2J9dBIJchOTk',
    appId: '1:316349124552:ios:d50537efefb0cec37dfafd',
    messagingSenderId: '316349124552',
    projectId: 'arcloudanchor-12fd3',
    databaseURL:
        'https://arcloudanchor-12fd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcloudanchor-12fd3.firebasestorage.app',
    iosBundleId: 'com.example.tagnarMerchant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZF9Q0VvDW8UtZNQ5m3hkSc2B66vdpGM',
    appId: '1:316349124552:web:f891ca149187812a7dfafd',
    messagingSenderId: '316349124552',
    projectId: 'arcloudanchor-12fd3',
    authDomain: 'arcloudanchor-12fd3.firebaseapp.com',
    databaseURL:
        'https://arcloudanchor-12fd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arcloudanchor-12fd3.firebasestorage.app',
    measurementId: 'G-73NY4MVDFE',
  );
}
